### ISSUE TITLE
Game doesn't terminate properly when no play can be made.

### ISSUE THREAD

**Issue by AlexisSB** [MurrayT/COSC326#2]
The if statement checking for the draw counter/ pass counter in manager only checks it if a valid move is submitted, not if  repeated draws are made. Check line 214 -217. Should be outside of legal move if else.

**Comment by MurrayT** [comment]
Newest version just pushed should fix this bug. If you have access to the board that failed before can you try and run it with the newest? I'll then close this issue

**Comment by AlexisSB** [comment]
Ran 1000 tests again and couldn't get it to stall and keep discarding so should be good.
